#!/usr/bin/env bash
# 裸机配置 EMQX 5：
#  1) 以 systemd 环境变量固定 Dashboard 初始账号（免首次强制改密）；
#  2) 在 /etc/emqx/emqx.conf 追加 8883 SSL listener（证书用 20_certs 产物）；
#  3) 调用通用 configure-emqx.py（回调指向本机 127.0.0.1 后端）。
# 幂等：重复执行安全（配置脚本内部均为「已存在则更新」语义）。
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../lib/common.sh
. "$HERE/lib/common.sh"
load_config "$HERE"

require_root
command -v emqx >/dev/null 2>&1 || die "未安装 EMQX，请先执行 00_install_deps。"
command -v python3 >/dev/null 2>&1 || die "需要 python3（一般系统自带；apt: python3）。"

DASH_U="${EMQX_DASHBOARD_USER:-admin}"
DASH_PORT="${EMQX_DASHBOARD_PORT:-18083}"
SRV_U="${MQTT_SERVER_USER:-wendao_server}"
KEYNAME="${EMQX_API_KEY_NAME:-wendao-backend-kick}"

# ---- Dashboard 初始密码（生成并落盘复用）----
DASH_F="$SECRET_DIR/emqx_dashboard_password"
if [ -n "${EMQX_DASHBOARD_PASSWORD:-}" ]; then
  printf '%s' "$EMQX_DASHBOARD_PASSWORD" > "$DASH_F"
fi
DASH_PW="$(get_secret emqx_dashboard_password)"

# 平台账号密码（后端自身连 broker）
SRV_PW_F="$SECRET_DIR/mqtt_server_password"
if [ -n "${MQTT_SERVER_PASSWORD:-}" ]; then
  printf '%s' "$MQTT_SERVER_PASSWORD" > "$SRV_PW_F"
fi
SRV_PW="$(get_secret mqtt_server_password)"

# EMQX auth/acl 回调共享密钥（与后端 mqtt_auth_secret 一致）
HOOK_PW="$(get_secret mqtt_hook_secret)"

# ---- systemd 注入 Dashboard 默认账号 ----
mkdir -p /etc/systemd/system/emqx.service.d
cat > /etc/systemd/system/emqx.service.d/credentials.conf <<EOF
[Service]
Environment=EMQX_DASHBOARD__DEFAULT_USERNAME=${DASH_U}
Environment=EMQX_DASHBOARD__DEFAULT_PASSWORD=${DASH_PW}
EOF
systemctl daemon-reload

# ---- 追加 8883 SSL listener（仅追加一次，标记幂等）----
EMQX_ETC=/etc/emqx/emqx.conf
[ -f "$EMQX_ETC" ] || EMQX_ETC="$(find /etc -name emqx.conf -path '*emqx*' 2>/dev/null | head -1)"
[ -n "$EMQX_ETC" ] && [ -f "$EMQX_ETC" ] || die "找不到 emqx 配置文件。"

if ! grep -q "# wendao-managed-ssl" "$EMQX_ETC"; then
  cat >> "$EMQX_ETC" <<EOF

# wendao-managed-ssl: 8883 mqtts (generated by deploy/linux)
listeners.ssl.default {
  enabled = true
  bind = "0.0.0.0:${MQTT_TLS_PORT:-8883}"
  ssl_options {
    cacertfile = "${CERT_DIR}/ca.crt"
    certfile   = "${CERT_DIR}/server.crt"
    keyfile    = "${CERT_DIR}/server.key"
    verify     = verify_none
  }
}
EOF
  log "已向 $EMQX_ETC 追加 SSL listener。"
fi

log "重启 EMQX 以加载 Dashboard 默认账号……"
systemctl daemon-reload
systemctl enable emqx >/dev/null 2>&1
systemctl restart emqx
# 等待 Dashboard 端口
for i in $(seq 1 40); do
  if curl -fsS "http://127.0.0.1:$DASH_PORT" >/dev/null 2>&1; then break; fi
  sleep 2
done

# ---- 生成给 python 配置脚本用的临时 env 文件 ----
PY_ENV="$(mktemp)"; trap 'rm -f "$PY_ENV"' EXIT
cat > "$PY_ENV" <<EOF
EMQX_DASHBOARD_PORT=$DASH_PORT
EMQX_DASHBOARD_USER=$DASH_U
EMQX_DASHBOARD_PASSWORD=$DASH_PW
MQTT_SERVER_USER=$SRV_U
MQTT_SERVER_PASSWORD=$SRV_PW
MQTT_HOOK_SECRET=$HOOK_PW
EMQX_API_KEY_NAME=$KEYNAME
SERVER_PORT=${SERVER_PORT:-8080}
EOF

API_ENV_F="$SECRET_DIR/emqx_api.env"
log "执行 EMQX 认证/ACL 自动配置（回调 http://127.0.0.1:${SERVER_PORT:-8080}）……"
python3 "$REPO_ROOT/deploy/docker/configure-emqx.py" \
  --skip-default-env \
  --env-file "$PY_ENV" \
  --callback-host 127.0.0.1 \
  --out "$API_ENV_F"

log "EMQX 配置完成。互踢凭据：$API_ENV_F"
info "Dashboard：http://<server-ip>:$DASH_PORT  账号 $DASH_U 密码 $DASH_F"
