server:
  port: 8080
  jwt_secret: "wendaoiot-secret-key"

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ""
  database: wendaoiot

mqtt:
  broker: tcp://pannel.wendaoiot.com:1883
  client_id: wendao_server
  username: ""
  password: ""
